/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallRouteImport } from './routes/call'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ManageSellerRouteImport } from './routes/manage-seller'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PersonalityRouteImport } from './routes/personality'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SellerProfileRouteImport } from './routes/seller-profile'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSellerRoute = ManageSellerRouteImport.update({
  id: '/manage-seller',
  path: '/manage-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalityRoute = PersonalityRouteImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/seller-profile',
  path: '/seller-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/manage-seller': typeof ManageSellerRoute
  '/order': typeof OrderRoute
  '/personality': typeof PersonalityRoute
  '/replay': typeof ReplayRoute
  '/result': typeof ResultRoute
  '/sell': typeof SellRoute
  '/seller-profile': typeof SellerProfileRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/manage-seller': typeof ManageSellerRoute
  '/order': typeof OrderRoute
  '/personality': typeof PersonalityRoute
  '/replay': typeof ReplayRoute
  '/result': typeof ResultRoute
  '/sell': typeof SellRoute
  '/seller-profile': typeof SellerProfileRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call': typeof CallRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/manage-seller': typeof ManageSellerRoute
  '/order': typeof OrderRoute
  '/personality': typeof PersonalityRoute
  '/replay': typeof ReplayRoute
  '/result': typeof ResultRoute
  '/sell': typeof SellRoute
  '/seller-profile': typeof SellerProfileRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/delivery'
    | '/manage-seller'
    | '/order'
    | '/personality'
    | '/replay'
    | '/result'
    | '/sell'
    | '/seller-profile'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/delivery'
    | '/manage-seller'
    | '/order'
    | '/personality'
    | '/replay'
    | '/result'
    | '/sell'
    | '/seller-profile'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/call'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/delivery'
    | '/manage-seller'
    | '/order'
    | '/personality'
    | '/replay'
    | '/result'
    | '/sell'
    | '/seller-profile'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallRoute: typeof CallRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  ManageSellerRoute: typeof ManageSellerRoute
  OrderRoute: typeof OrderRoute
  PersonalityRoute: typeof PersonalityRoute
  ReplayRoute: typeof ReplayRoute
  ResultRoute: typeof ResultRoute
  SellRoute: typeof SellRoute
  SellerProfileRoute: typeof SellerProfileRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-seller': {
      id: '/manage-seller'
      path: '/manage-seller'
      fullPath: '/manage-seller'
      preLoaderRoute: typeof ManageSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personality': {
      id: '/personality'
      path: '/personality'
      fullPath: '/personality'
      preLoaderRoute: typeof PersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-profile': {
      id: '/seller-profile'
      path: '/seller-profile'
      fullPath: '/seller-profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallRoute: CallRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  ManageSellerRoute: ManageSellerRoute,
  OrderRoute: OrderRoute,
  PersonalityRoute: PersonalityRoute,
  ReplayRoute: ReplayRoute,
  ResultRoute: ResultRoute,
  SellRoute: SellRoute,
  SellerProfileRoute: SellerProfileRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
